@startuml
class VgaTextModeCursor {
    + row: uint8_t 
    + col: uint8_t
    + memory_position: uint16_t <<Pointer>> 
    + memory_start: uint16_t <<Pointer>> 
    + memory_end: uint16_t <<Pointer>> 
    + CalculateRowColFromMemoryPosition(c:VgaTextModeCursor <<Pointer>>):void
}
class VgaTextModeInterface {
    + cursor:VgaTextModeCursor
    + Print(a:VgaTextModeInterface <<Pointer>>, input:char[*] <<Pointer>>, attribute:uint8_t)
    + NewVgaTextModeInterface():VgaTextModeInterface <<Create>> 
}
VgaTextModeCursor --* VgaTextModeInterface
@enduml