#include "keyboard.h"
#include "stdbool.h"

void push_scancode_buffer(scancode_buffer_t *buffer, uint8_t scancode)
{
    *buffer->head = scancode;
    buffer->head = (buffer->head - buffer->buffer + 1) % 256 + buffer->buffer;
}

uint8_t pop_scancode_buffer(scancode_buffer_t *buffer)
{
    uint8_t* tail = (buffer->head - buffer->buffer - 1 + 256) % 256 + buffer->buffer;
    uint8_t value = *tail;
    *tail = 0;
    return value;
}

scancode_buffer_t create_scancode_buffer()
{
    scancode_buffer_t buffer = {0};
    buffer.head = buffer.buffer;
}

void push_keycode_buffer(keycode_buffer_t *buffer, keycode_t keycode)
{
    *buffer->head = keycode;
    buffer->head = (buffer->head - buffer->buffer + 1) % 256 + buffer->buffer;
}

keycode_t pop_keycode_buffer(keycode_buffer_t *buffer)
{
    keycode_t* tail = (buffer->head - buffer->buffer - 1 + 256) % 256 + buffer->buffer;
    keycode_t value = *tail;
    *tail = (keycode_t){0};
    return value;
}

keycode_buffer_t create_keycode_buffer()
{
    keycode_buffer_t buffer = {0};
    buffer.head = buffer.buffer;
}

void scancode2keycode(scancode_buffer_t *input, keycode_buffer_t *output)
{
    uint8_t key = pop_scancode_buffer(input);
    switch (key){
// This code is generated by a Python script
case 0x01: keycode_t keycode = new_keycode(110,false);	push_keycode_buffer(output, keycode); break;	/* Esc	down */
case 0x81: keycode_t keycode = new_keycode(110,true);	push_keycode_buffer(output, keycode); break;	/* Esc	up */
case 0x02: keycode_t keycode = new_keycode(2,false);	push_keycode_buffer(output, keycode); break;	/* 1	down */
case 0x82: keycode_t keycode = new_keycode(2,true);	push_keycode_buffer(output, keycode); break;	/* 1	up */
case 0x03: keycode_t keycode = new_keycode(3,false);	push_keycode_buffer(output, keycode); break;	/* 2	down */
case 0x83: keycode_t keycode = new_keycode(3,true);	push_keycode_buffer(output, keycode); break;	/* 2	up */
case 0x04: keycode_t keycode = new_keycode(4,false);	push_keycode_buffer(output, keycode); break;	/* 3	down */
case 0x84: keycode_t keycode = new_keycode(4,true);	push_keycode_buffer(output, keycode); break;	/* 3	up */
case 0x05: keycode_t keycode = new_keycode(5,false);	push_keycode_buffer(output, keycode); break;	/* 4	down */
case 0x85: keycode_t keycode = new_keycode(5,true);	push_keycode_buffer(output, keycode); break;	/* 4	up */
case 0x06: keycode_t keycode = new_keycode(6,false);	push_keycode_buffer(output, keycode); break;	/* 5	down */
case 0x86: keycode_t keycode = new_keycode(6,true);	push_keycode_buffer(output, keycode); break;	/* 5	up */
case 0x07: keycode_t keycode = new_keycode(7,false);	push_keycode_buffer(output, keycode); break;	/* 6	down */
case 0x87: keycode_t keycode = new_keycode(7,true);	push_keycode_buffer(output, keycode); break;	/* 6	up */
case 0x08: keycode_t keycode = new_keycode(8,false);	push_keycode_buffer(output, keycode); break;	/* 7	down */
case 0x88: keycode_t keycode = new_keycode(8,true);	push_keycode_buffer(output, keycode); break;	/* 7	up */
case 0x09: keycode_t keycode = new_keycode(9,false);	push_keycode_buffer(output, keycode); break;	/* 8	down */
case 0x89: keycode_t keycode = new_keycode(9,true);	push_keycode_buffer(output, keycode); break;	/* 8	up */
case 0x0A: keycode_t keycode = new_keycode(10,false);	push_keycode_buffer(output, keycode); break;	/* 9	down */
case 0x8A: keycode_t keycode = new_keycode(10,true);	push_keycode_buffer(output, keycode); break;	/* 9	up */
case 0x0B: keycode_t keycode = new_keycode(11,false);	push_keycode_buffer(output, keycode); break;	/* 0	down */
case 0x8B: keycode_t keycode = new_keycode(11,true);	push_keycode_buffer(output, keycode); break;	/* 0	up */
case 0x0C: keycode_t keycode = new_keycode(12,false);	push_keycode_buffer(output, keycode); break;	/* -	down */
case 0x8C: keycode_t keycode = new_keycode(12,true);	push_keycode_buffer(output, keycode); break;	/* -	up */
case 0x0D: keycode_t keycode = new_keycode(13,false);	push_keycode_buffer(output, keycode); break;	/* =	down */
case 0x8D: keycode_t keycode = new_keycode(13,true);	push_keycode_buffer(output, keycode); break;	/* =	up */
case 0x0E: keycode_t keycode = new_keycode(15,false);	push_keycode_buffer(output, keycode); break;	/* Backspace	down */
case 0x8E: keycode_t keycode = new_keycode(15,true);	push_keycode_buffer(output, keycode); break;	/* Backspace	up */
case 0x0F: keycode_t keycode = new_keycode(16,false);	push_keycode_buffer(output, keycode); break;	/* Tab	down */
case 0x8F: keycode_t keycode = new_keycode(16,true);	push_keycode_buffer(output, keycode); break;	/* Tab	up */
case 0x10: keycode_t keycode = new_keycode(17,false);	push_keycode_buffer(output, keycode); break;	/* q	down */
case 0x90: keycode_t keycode = new_keycode(17,true);	push_keycode_buffer(output, keycode); break;	/* q	up */
case 0x11: keycode_t keycode = new_keycode(18,false);	push_keycode_buffer(output, keycode); break;	/* w	down */
case 0x91: keycode_t keycode = new_keycode(18,true);	push_keycode_buffer(output, keycode); break;	/* w	up */
case 0x12: keycode_t keycode = new_keycode(19,false);	push_keycode_buffer(output, keycode); break;	/* e	down */
case 0x92: keycode_t keycode = new_keycode(19,true);	push_keycode_buffer(output, keycode); break;	/* e	up */
case 0x13: keycode_t keycode = new_keycode(20,false);	push_keycode_buffer(output, keycode); break;	/* r	down */
case 0x93: keycode_t keycode = new_keycode(20,true);	push_keycode_buffer(output, keycode); break;	/* r	up */
case 0x14: keycode_t keycode = new_keycode(21,false);	push_keycode_buffer(output, keycode); break;	/* t	down */
case 0x94: keycode_t keycode = new_keycode(21,true);	push_keycode_buffer(output, keycode); break;	/* t	up */
case 0x15: keycode_t keycode = new_keycode(22,false);	push_keycode_buffer(output, keycode); break;	/* y	down */
case 0x95: keycode_t keycode = new_keycode(22,true);	push_keycode_buffer(output, keycode); break;	/* y	up */
case 0x16: keycode_t keycode = new_keycode(23,false);	push_keycode_buffer(output, keycode); break;	/* u	down */
case 0x96: keycode_t keycode = new_keycode(23,true);	push_keycode_buffer(output, keycode); break;	/* u	up */
case 0x17: keycode_t keycode = new_keycode(24,false);	push_keycode_buffer(output, keycode); break;	/* i	down */
case 0x97: keycode_t keycode = new_keycode(24,true);	push_keycode_buffer(output, keycode); break;	/* i	up */
case 0x18: keycode_t keycode = new_keycode(25,false);	push_keycode_buffer(output, keycode); break;	/* o	down */
case 0x98: keycode_t keycode = new_keycode(25,true);	push_keycode_buffer(output, keycode); break;	/* o	up */
case 0x19: keycode_t keycode = new_keycode(26,false);	push_keycode_buffer(output, keycode); break;	/* p	down */
case 0x99: keycode_t keycode = new_keycode(26,true);	push_keycode_buffer(output, keycode); break;	/* p	up */
case 0x1A: keycode_t keycode = new_keycode(27,false);	push_keycode_buffer(output, keycode); break;	/* [	down */
case 0x9A: keycode_t keycode = new_keycode(27,true);	push_keycode_buffer(output, keycode); break;	/* [	up */
case 0x1B: keycode_t keycode = new_keycode(28,false);	push_keycode_buffer(output, keycode); break;	/* ]	down */
case 0x9B: keycode_t keycode = new_keycode(28,true);	push_keycode_buffer(output, keycode); break;	/* ]	up */
case 0x1C: keycode_t keycode = new_keycode(43,false);	push_keycode_buffer(output, keycode); break;	/* Enter	down */
case 0x9C: keycode_t keycode = new_keycode(43,true);	push_keycode_buffer(output, keycode); break;	/* Enter	up */
case 0x1D: keycode_t keycode = new_keycode(58,false);	push_keycode_buffer(output, keycode); break;	/* Left Ctrl	down */
case 0x9D: keycode_t keycode = new_keycode(58,true);	push_keycode_buffer(output, keycode); break;	/* Left Ctrl	up */
case 0x1E: keycode_t keycode = new_keycode(31,false);	push_keycode_buffer(output, keycode); break;	/* a	down */
case 0x9E: keycode_t keycode = new_keycode(31,true);	push_keycode_buffer(output, keycode); break;	/* a	up */
case 0x1F: keycode_t keycode = new_keycode(32,false);	push_keycode_buffer(output, keycode); break;	/* s	down */
case 0x9F: keycode_t keycode = new_keycode(32,true);	push_keycode_buffer(output, keycode); break;	/* s	up */
case 0x20: keycode_t keycode = new_keycode(33,false);	push_keycode_buffer(output, keycode); break;	/* d	down */
case 0xA0: keycode_t keycode = new_keycode(33,true);	push_keycode_buffer(output, keycode); break;	/* d	up */
case 0x21: keycode_t keycode = new_keycode(34,false);	push_keycode_buffer(output, keycode); break;	/* f	down */
case 0xA1: keycode_t keycode = new_keycode(34,true);	push_keycode_buffer(output, keycode); break;	/* f	up */
case 0x22: keycode_t keycode = new_keycode(35,false);	push_keycode_buffer(output, keycode); break;	/* g	down */
case 0xA2: keycode_t keycode = new_keycode(35,true);	push_keycode_buffer(output, keycode); break;	/* g	up */
case 0x23: keycode_t keycode = new_keycode(36,false);	push_keycode_buffer(output, keycode); break;	/* h	down */
case 0xA3: keycode_t keycode = new_keycode(36,true);	push_keycode_buffer(output, keycode); break;	/* h	up */
case 0x24: keycode_t keycode = new_keycode(37,false);	push_keycode_buffer(output, keycode); break;	/* j	down */
case 0xA4: keycode_t keycode = new_keycode(37,true);	push_keycode_buffer(output, keycode); break;	/* j	up */
case 0x25: keycode_t keycode = new_keycode(38,false);	push_keycode_buffer(output, keycode); break;	/* k	down */
case 0xA5: keycode_t keycode = new_keycode(38,true);	push_keycode_buffer(output, keycode); break;	/* k	up */
case 0x26: keycode_t keycode = new_keycode(39,false);	push_keycode_buffer(output, keycode); break;	/* l	down */
case 0xA6: keycode_t keycode = new_keycode(39,true);	push_keycode_buffer(output, keycode); break;	/* l	up */
case 0x27: keycode_t keycode = new_keycode(40,false);	push_keycode_buffer(output, keycode); break;	/* ;	down */
case 0xA7: keycode_t keycode = new_keycode(40,true);	push_keycode_buffer(output, keycode); break;	/* ;	up */
case 0x28: keycode_t keycode = new_keycode(41,false);	push_keycode_buffer(output, keycode); break;	/* '	down */
case 0xA8: keycode_t keycode = new_keycode(41,true);	push_keycode_buffer(output, keycode); break;	/* '	up */
case 0x29: keycode_t keycode = new_keycode(1,false);	push_keycode_buffer(output, keycode); break;	/* `	down */
case 0xA9: keycode_t keycode = new_keycode(1,true);	push_keycode_buffer(output, keycode); break;	/* `	up */
case 0x2A: keycode_t keycode = new_keycode(44,false);	push_keycode_buffer(output, keycode); break;	/* Left Shift	down */
case 0xAA: keycode_t keycode = new_keycode(44,true);	push_keycode_buffer(output, keycode); break;	/* Left Shift	up */
case 0x2B: keycode_t keycode = new_keycode(29,false);	push_keycode_buffer(output, keycode); break;	/* \	down */
case 0xAB: keycode_t keycode = new_keycode(29,true);	push_keycode_buffer(output, keycode); break;	/* \	up */
case 0x2C: keycode_t keycode = new_keycode(46,false);	push_keycode_buffer(output, keycode); break;	/* z	down */
case 0xAC: keycode_t keycode = new_keycode(46,true);	push_keycode_buffer(output, keycode); break;	/* z	up */
case 0x2D: keycode_t keycode = new_keycode(47,false);	push_keycode_buffer(output, keycode); break;	/* x	down */
case 0xAD: keycode_t keycode = new_keycode(47,true);	push_keycode_buffer(output, keycode); break;	/* x	up */
case 0x2E: keycode_t keycode = new_keycode(48,false);	push_keycode_buffer(output, keycode); break;	/* c	down */
case 0xAE: keycode_t keycode = new_keycode(48,true);	push_keycode_buffer(output, keycode); break;	/* c	up */
case 0x2F: keycode_t keycode = new_keycode(49,false);	push_keycode_buffer(output, keycode); break;	/* v	down */
case 0xAF: keycode_t keycode = new_keycode(49,true);	push_keycode_buffer(output, keycode); break;	/* v	up */
case 0x30: keycode_t keycode = new_keycode(50,false);	push_keycode_buffer(output, keycode); break;	/* b	down */
case 0xB0: keycode_t keycode = new_keycode(50,true);	push_keycode_buffer(output, keycode); break;	/* b	up */
case 0x31: keycode_t keycode = new_keycode(51,false);	push_keycode_buffer(output, keycode); break;	/* n	down */
case 0xB1: keycode_t keycode = new_keycode(51,true);	push_keycode_buffer(output, keycode); break;	/* n	up */
case 0x32: keycode_t keycode = new_keycode(52,false);	push_keycode_buffer(output, keycode); break;	/* m	down */
case 0xB2: keycode_t keycode = new_keycode(52,true);	push_keycode_buffer(output, keycode); break;	/* m	up */
case 0x33: keycode_t keycode = new_keycode(53,false);	push_keycode_buffer(output, keycode); break;	/* ,	down */
case 0xB3: keycode_t keycode = new_keycode(53,true);	push_keycode_buffer(output, keycode); break;	/* ,	up */
case 0x34: keycode_t keycode = new_keycode(54,false);	push_keycode_buffer(output, keycode); break;	/* .	down */
case 0xB4: keycode_t keycode = new_keycode(54,true);	push_keycode_buffer(output, keycode); break;	/* .	up */
case 0x35: keycode_t keycode = new_keycode(55,false);	push_keycode_buffer(output, keycode); break;	/* /	down */
case 0xB5: keycode_t keycode = new_keycode(55,true);	push_keycode_buffer(output, keycode); break;	/* /	up */
case 0x36: keycode_t keycode = new_keycode(57,false);	push_keycode_buffer(output, keycode); break;	/* Right Shift	down */
case 0xB6: keycode_t keycode = new_keycode(57,true);	push_keycode_buffer(output, keycode); break;	/* Right Shift	up */
case 0x37: keycode_t keycode = new_keycode(100,false);	push_keycode_buffer(output, keycode); break;	/* Keypad *	down */
case 0xB7: keycode_t keycode = new_keycode(100,true);	push_keycode_buffer(output, keycode); break;	/* Keypad *	up */
case 0x38: keycode_t keycode = new_keycode(60,false);	push_keycode_buffer(output, keycode); break;	/* Left Alt	down */
case 0xB8: keycode_t keycode = new_keycode(60,true);	push_keycode_buffer(output, keycode); break;	/* Left Alt	up */
case 0x39: keycode_t keycode = new_keycode(61,false);	push_keycode_buffer(output, keycode); break;	/* Spacebar	down */
case 0xB9: keycode_t keycode = new_keycode(61,true);	push_keycode_buffer(output, keycode); break;	/* Spacebar	up */
case 0x3A: keycode_t keycode = new_keycode(30,false);	push_keycode_buffer(output, keycode); break;	/* Caps Lock	down */
case 0xBA: keycode_t keycode = new_keycode(30,true);	push_keycode_buffer(output, keycode); break;	/* Caps Lock	up */
case 0x3B: keycode_t keycode = new_keycode(112,false);	push_keycode_buffer(output, keycode); break;	/* F1	down */
case 0xBB: keycode_t keycode = new_keycode(112,true);	push_keycode_buffer(output, keycode); break;	/* F1	up */
case 0x3C: keycode_t keycode = new_keycode(113,false);	push_keycode_buffer(output, keycode); break;	/* F2	down */
case 0xBC: keycode_t keycode = new_keycode(113,true);	push_keycode_buffer(output, keycode); break;	/* F2	up */
case 0x3D: keycode_t keycode = new_keycode(114,false);	push_keycode_buffer(output, keycode); break;	/* F3	down */
case 0xBD: keycode_t keycode = new_keycode(114,true);	push_keycode_buffer(output, keycode); break;	/* F3	up */
case 0x3E: keycode_t keycode = new_keycode(115,false);	push_keycode_buffer(output, keycode); break;	/* F4	down */
case 0xBE: keycode_t keycode = new_keycode(115,true);	push_keycode_buffer(output, keycode); break;	/* F4	up */
case 0x3F: keycode_t keycode = new_keycode(116,false);	push_keycode_buffer(output, keycode); break;	/* F5	down */
case 0xBF: keycode_t keycode = new_keycode(116,true);	push_keycode_buffer(output, keycode); break;	/* F5	up */
case 0x40: keycode_t keycode = new_keycode(117,false);	push_keycode_buffer(output, keycode); break;	/* F6	down */
case 0xC0: keycode_t keycode = new_keycode(117,true);	push_keycode_buffer(output, keycode); break;	/* F6	up */
case 0x41: keycode_t keycode = new_keycode(118,false);	push_keycode_buffer(output, keycode); break;	/* F7	down */
case 0xC1: keycode_t keycode = new_keycode(118,true);	push_keycode_buffer(output, keycode); break;	/* F7	up */
case 0x42: keycode_t keycode = new_keycode(119,false);	push_keycode_buffer(output, keycode); break;	/* F8	down */
case 0xC2: keycode_t keycode = new_keycode(119,true);	push_keycode_buffer(output, keycode); break;	/* F8	up */
case 0x43: keycode_t keycode = new_keycode(120,false);	push_keycode_buffer(output, keycode); break;	/* F9	down */
case 0xC3: keycode_t keycode = new_keycode(120,true);	push_keycode_buffer(output, keycode); break;	/* F9	up */
case 0x44: keycode_t keycode = new_keycode(121,false);	push_keycode_buffer(output, keycode); break;	/* F10	down */
case 0xC4: keycode_t keycode = new_keycode(121,true);	push_keycode_buffer(output, keycode); break;	/* F10	up */
case 0x45: keycode_t keycode = new_keycode(90,false);	push_keycode_buffer(output, keycode); break;	/* Num Lock	down */
case 0xC5: keycode_t keycode = new_keycode(90,true);	push_keycode_buffer(output, keycode); break;	/* Num Lock	up */
case 0x46: keycode_t keycode = new_keycode(125,false);	push_keycode_buffer(output, keycode); break;	/* Scroll Lock	down */
case 0xC6: keycode_t keycode = new_keycode(125,true);	push_keycode_buffer(output, keycode); break;	/* Scroll Lock	up */
case 0x47: keycode_t keycode = new_keycode(91,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 7	down */
case 0xC7: keycode_t keycode = new_keycode(91,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 7	up */
case 0x48: keycode_t keycode = new_keycode(96,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 8	down */
case 0xC8: keycode_t keycode = new_keycode(96,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 8	up */
case 0x49: keycode_t keycode = new_keycode(101,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 9	down */
case 0xC9: keycode_t keycode = new_keycode(101,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 9	up */
case 0x4A: keycode_t keycode = new_keycode(105,false);	push_keycode_buffer(output, keycode); break;	/* Keypad -	down */
case 0xCA: keycode_t keycode = new_keycode(105,true);	push_keycode_buffer(output, keycode); break;	/* Keypad -	up */
case 0x4B: keycode_t keycode = new_keycode(92,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 4	down */
case 0xCB: keycode_t keycode = new_keycode(92,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 4	up */
case 0x4C: keycode_t keycode = new_keycode(97,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 5	down */
case 0xCC: keycode_t keycode = new_keycode(97,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 5	up */
case 0x4D: keycode_t keycode = new_keycode(102,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 6	down */
case 0xCD: keycode_t keycode = new_keycode(102,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 6	up */
case 0x4E: keycode_t keycode = new_keycode(106,false);	push_keycode_buffer(output, keycode); break;	/* Keypad +	down */
case 0xCE: keycode_t keycode = new_keycode(106,true);	push_keycode_buffer(output, keycode); break;	/* Keypad +	up */
case 0x4F: keycode_t keycode = new_keycode(93,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 1	down */
case 0xCF: keycode_t keycode = new_keycode(93,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 1	up */
case 0x50: keycode_t keycode = new_keycode(98,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 2	down */
case 0xD0: keycode_t keycode = new_keycode(98,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 2	up */
case 0x51: keycode_t keycode = new_keycode(103,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 3	down */
case 0xD1: keycode_t keycode = new_keycode(103,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 3	up */
case 0x52: keycode_t keycode = new_keycode(99,false);	push_keycode_buffer(output, keycode); break;	/* Keypad 0	down */
case 0xD2: keycode_t keycode = new_keycode(99,true);	push_keycode_buffer(output, keycode); break;	/* Keypad 0	up */
case 0x53: keycode_t keycode = new_keycode(104,false);	push_keycode_buffer(output, keycode); break;	/* Keypad .	down */
case 0xD3: keycode_t keycode = new_keycode(104,true);	push_keycode_buffer(output, keycode); break;	/* Keypad .	up */
case 0x57: keycode_t keycode = new_keycode(122,false);	push_keycode_buffer(output, keycode); break;	/* F11	down */
case 0xD7: keycode_t keycode = new_keycode(122,true);	push_keycode_buffer(output, keycode); break;	/* F11	up */
case 0x58: keycode_t keycode = new_keycode(123,false);	push_keycode_buffer(output, keycode); break;	/* F12	down */
case 0xD8: keycode_t keycode = new_keycode(123,true);	push_keycode_buffer(output, keycode); break;	/* F12	up */
case 0xE0: uint8_t key = pop_scancode_buffer(input); switch (key){
case 0x1C: keycode_t keycode = new_keycode(108,false);	push_keycode_buffer(output, keycode); break;	/* Keypad Enter	down */
case 0x9C: keycode_t keycode = new_keycode(108,true);	push_keycode_buffer(output, keycode); break;	/* Keypad Enter	up */
case 0x1D: keycode_t keycode = new_keycode(64,false);	push_keycode_buffer(output, keycode); break;	/* Right Ctrl	down */
case 0x9D: keycode_t keycode = new_keycode(64,true);	push_keycode_buffer(output, keycode); break;	/* Right Ctrl	up */
case 0x35: keycode_t keycode = new_keycode(95,false);	push_keycode_buffer(output, keycode); break;	/* Keypad /	down */
case 0xB5: keycode_t keycode = new_keycode(95,true);	push_keycode_buffer(output, keycode); break;	/* Keypad /	up */
case 0x38: keycode_t keycode = new_keycode(62,false);	push_keycode_buffer(output, keycode); break;	/* Right Alt	down */
case 0xB8: keycode_t keycode = new_keycode(62,true);	push_keycode_buffer(output, keycode); break;	/* Right Alt	up */
case 0x47: keycode_t keycode = new_keycode(80,false);	push_keycode_buffer(output, keycode); break;	/* Home	down */
case 0xC7: keycode_t keycode = new_keycode(80,true);	push_keycode_buffer(output, keycode); break;	/* Home	up */
case 0x48: keycode_t keycode = new_keycode(83,false);	push_keycode_buffer(output, keycode); break;	/* Up Arrow	down */
case 0xC8: keycode_t keycode = new_keycode(83,true);	push_keycode_buffer(output, keycode); break;	/* Up Arrow	up */
case 0x49: keycode_t keycode = new_keycode(85,false);	push_keycode_buffer(output, keycode); break;	/* Page Up	down */
case 0xC9: keycode_t keycode = new_keycode(85,true);	push_keycode_buffer(output, keycode); break;	/* Page Up	up */
case 0x4B: keycode_t keycode = new_keycode(79,false);	push_keycode_buffer(output, keycode); break;	/* Left Arrow	down */
case 0xCB: keycode_t keycode = new_keycode(79,true);	push_keycode_buffer(output, keycode); break;	/* Left Arrow	up */
// case 0x4B: keycode_t keycode = new_keycode(76,false);	push_keycode_buffer(output, keycode); break;	/* Delete	down */
// case 0xCB: keycode_t keycode = new_keycode(76,true);	push_keycode_buffer(output, keycode); break;	/* Delete	up */
case 0x4D: keycode_t keycode = new_keycode(89,false);	push_keycode_buffer(output, keycode); break;	/* Right Arrow	down */
case 0xCD: keycode_t keycode = new_keycode(89,true);	push_keycode_buffer(output, keycode); break;	/* Right Arrow	up */
case 0x4F: keycode_t keycode = new_keycode(81,false);	push_keycode_buffer(output, keycode); break;	/* End	down */
case 0xCF: keycode_t keycode = new_keycode(81,true);	push_keycode_buffer(output, keycode); break;	/* End	up */
case 0x50: keycode_t keycode = new_keycode(84,false);	push_keycode_buffer(output, keycode); break;	/* Down Arrow	down */
case 0xD0: keycode_t keycode = new_keycode(84,true);	push_keycode_buffer(output, keycode); break;	/* Down Arrow	up */
case 0x51: keycode_t keycode = new_keycode(86,false);	push_keycode_buffer(output, keycode); break;	/* Page Down	down */
case 0xD1: keycode_t keycode = new_keycode(86,true);	push_keycode_buffer(output, keycode); break;	/* Page Down	up */
case 0x52: keycode_t keycode = new_keycode(75,false);	push_keycode_buffer(output, keycode); break;	/* Insert	down */
case 0xD2: keycode_t keycode = new_keycode(75,true);	push_keycode_buffer(output, keycode); break;	/* Insert	up */ 
// Manual code
case 0x2A: if (pop_scancode_buffer(input) == 0xE0){ if (pop_scancode_buffer(input) == 0x37){
    keycode_t keycode = new_keycode(124, false);
    push_keycode_buffer(output, keycode);
}}
break;
case 0xB7: if(pop_scancode_buffer(input) == 0xE0){ if(pop_scancode_buffer(input) == 0xAA){
    keycode_t keycode = new_keycode(124, true);
    push_keycode_buffer(output, keycode);
}}
break;
}
case 0xE1: uint8_t key = pop_scancode_buffer(input); switch (key){
    case 0x1D: if(pop_scancode_buffer(input) == 0x45){
        keycode_t keycode = new_keycode(126, false);
        push_keycode_buffer(output, keycode);
    }
    break;
    case 0x9D: if (pop_scancode_buffer(input) == 0xC5){
        keycode_t keycode = new_keycode(126, true);
        push_keycode_buffer(output, keycode);
    }
// End manual code
}
// ^ That code was generated by a Python script



    }
}
