name: Generate Documentation

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write # Required for actions-gh-pages to push to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Doxygen Docs
        uses: mattnotmitt/doxygen-action@edge

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxygen-out/html
